name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: AI Code Review
        uses: se0kcess/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: 'gpt-3.5-turbo'
          language: 'Korean'
          system_message: |
            당신은 시니어 개발자입니다.
            다음 규칙에 따라 코드를 리뷰해주세요:
            1. 코드의 품질, 가독성, 유지보수성을 중점적으로 검토합니다.
            2. 구체적인 개선 제안을 해주세요.
            3. 긍정적인 피드백도 함께 제공해주세요.
            4. 한국어로 친근하고 명확하게 설명해주세요.
            5. 보안, 성능, 확장성 관련 이슈도 체크해주세요.

          max_files: 5
          exclude_patterns: |
            **/*.json
            **/*.md
            **/*.lock
